name: pits
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  domain:
    path: ./modules/domain
  infrastructure:
    path: ./modules/infrastructure
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  injectable: ^2.5.1
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.8.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true

  