name: infrastructure
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  mockito: ^5.4.5
  get_it: ^8.0.3
  injectable: ^2.5.0 

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0